# -*- coding: utf-8 -*-
"""add3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQ1mLjq_sgyMgxsSCd_UneL_UZ_AhkTb
"""



import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv('Salary Data.csv')
    df.dropna(inplace=True)
    return df

# Preprocess and train model
def train_model(df):
    le_gender = LabelEncoder()
    le_edu = LabelEncoder()
    le_job = LabelEncoder()

    df['Gender'] = le_gender.fit_transform(df['Gender'])
    df['Education Level'] = le_edu.fit_transform(df['Education Level'])
    df['Job Title'] = le_job.fit_transform(df['Job Title'])

    X = df[['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience']]
    y = df['Salary']

    model = LinearRegression()
    model.fit(X, y)

    return model, le_gender, le_edu, le_job

# Load and train
data = load_data()
model, le_gender, le_edu, le_job = train_model(data)

# Streamlit UI
st.title("💼 Salary Prediction App")
st.write("Enter your details to predict your estimated salary:")

age = st.number_input("Age", min_value=18, max_value=100, step=1)
gender = st.selectbox("Gender", data['Gender'].unique())
edu_level = st.selectbox("Education Level", data['Education Level'].unique())
job_title = st.selectbox("Job Title", data['Job Title'].unique())
experience = st.slider("Years of Experience", min_value=0, max_value=50)

# Predict button
if st.button("Predict Salary"):
    gender_encoded = le_gender.transform([gender])[0]
    edu_encoded = le_edu.transform([edu_level])[0]
    job_encoded = le_job.transform([job_title])[0]

    features = np.array([[age, gender_encoded, edu_encoded, job_encoded, experience]])
    prediction = model.predict(features)

    st.success(f"💰 Estimated Salary: ₹{prediction[0]:,.2f}")
