# -*- coding: utf-8 -*-
"""SalaryPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kkxTECC8h0jE-uDwTJjXGKIP0fqg6FT8
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

saldf=pd.read_csv('/content/Salary Data.csv')
saldf.head()

saldf.isnull().sum()

saldf.dropna(inplace=True)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le1=LabelEncoder()
le2=LabelEncoder()
saldf['Gender']=le.fit_transform(saldf['Gender'])
saldf['Education Level']=le1.fit_transform(saldf['Education Level'])
saldf['Job Title']=le2.fit_transform(saldf['Job Title'])

a=saldf[['Age','Gender','Education Level','Job Title','Years of Experience']]
b=saldf['Salary']

LR=LinearRegression()

LR.fit(a,b)

LR.predict([[43,0,0,0,4]])